### ISSUE TITLE
Add ability to change NFT rarity weight separator

### ISSUE THREAD

**Issue by PavelMal** [UniqueNetwork/mass-nfts-doc#8]
I wanted to mint NFT collection but I faced an issue that there is a '%' sign in the name of my collection attributes

When I run script: `node 0-generate-nfts.js`

Got:
```
RangeError: Invalid array length
    at selectAttribute (/Users/pmalykh/Documents/projects/unique/mass-nfts-doc/0-generate-nfts.js:20:28)
    at getNFTAttributes (/Users/pmalykh/Documents/projects/unique/mass-nfts-doc/0-generate-nfts.js:29:14)
    at /Users/pmalykh/Documents/projects/unique/mass-nfts-doc/0-generate-nfts.js:38:46
    at Array.map (<anonymous>)
    at generateNftsData (/Users/pmalykh/Documents/projects/unique/mass-nfts-doc/0-generate-nfts.js:38:22)
    at g
```

So my suggestion is adding ability to specify custom weight separator in the config file

**Comment by PavelMal** [comment]
Added PR: https://github.com/UniqueNetwork/mass-nfts-doc/pull/9

Could you check it please?

**Comment by Maksandre** [comment]
merged

**Comment by PavelMal** [comment]
thank you!
